update requirements
GSA/inventory-app pull request #248
Opened 2021-02-17 19:28 UTC by FuhuXia

2021-02-17 20:46 UTC, jbrown-xentity approved these changes

2021-02-17 20:47 UTC, jbrown-xentity requested changes

2021-02-17 20:47 UTC, jbrown-xentity commented on requirements-freeze.txt
> --e git+https://github.com/GSA/inventory-app.git@4117e40dd38ded07fc458d13e0d7ce330e90c50b#egg=ckanext_datagov_inventory&subdirectory=ckanext-datagov_inventory
I don't believe this should be removed, I thought @adborden fixed this in main...

2021-02-19 17:12 UTC, adborden commented
Thanks @FuhuXia I'll take care of this update in https://github.com/GSA/inventory-app/pull/247 since I'm refactoring the requirements.txt.

2021-02-19 17:12 UTC, closed without merging